version: '3'
services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - "${CATALOG:-.}/:/app"
    ports:
      - "${HTTP_PORT:-8000}:80"
    depends_on:
      - postgres
    container_name: symfony

  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: main
    ports:
      - '5435:5432'

volumes:
  postgres_data: