parameters:

services:
    _defaults:
        autowire: true     
        autoconfigure: true 

    CompanyInfoApi\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
