name: Symfony Build

on:
    push:
        branches:
            - main
            - develop
    pull_request: ~

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:alpine
                env:
                    POSTGRES_PASSWORD: main
                    POSTGRES_USER: main
                    POSTGRES_DB: main
                ports:
                    - 5435:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: mbstring, intl, pdo_pgsql
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --no-progress --no-suggest

            - name: Prepare the database
              run: php bin/console doctrine:database:create --if-not-exists
              env:
                  DATABASE_URL: postgresql://main:main@localhost:5435/main

            - name: Run the database migrations
              run: php bin/console doctrine:migrations:migrate --no-interaction

            - name: Run ECS
              run: vendor/bin/ecs

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse -c phpstan.dist.neon -l 8 src/